version: '{build}'
clone_depth: 10
install:
- cmd: git submodule update --init --recursive
nuget:
  project_feed: true
  disable_publish_on_pr: true
build:
  verbosity: minimal
before_build:
- ps: Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER
- ps: Write-Host $env:APPVEYOR_REPO_BRANCH
build_script:
- ps: >-
    If($env:APPVEYOR_REPO_BRANCH -eq 'master'){ .\build.cmd Publish }
    Else { .\build.cmd Default }
test: off
artifacts:
- path: bin/Freya.*.nupkg
  name: nuget
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/289b3f174c2b681ff11a
